apiVersion: v1
kind: Secret
metadata:
  name: traefik-admin
  namespace: default

data:
  users: |2
    <your user and password hash base64 encoded> # create the string with 'htpasswd -nb user password | openssl base64' and paste it here 
    # look at https://docs.traefik.io/middlewares/basicauth/
